### PR TITLE
Amazon - A.C.M.E.

### PR DESCRIPTION
**Pull request by ilFratus**
Initial implementation for amazon ADV and Acme geo-position

### CODE REVIEW

**Comment by gabrieledarrigo** [comment]
:+1: Nice work!
Is it complete?

**Comment by ilFratus** [comment]
Yes, Acme issue and Amazon's ADV banner both

**Comment by gabrieledarrigo** [comment]
Mhhh ok, but I'm not totally satisfied with this solution.
Can You please convert this Javascript Object literals into a valid JSON?

Here's the JSON documentation:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON

(mostly simple difference is that property names (the keys) must be double-quoted strings; trailing commas are forbidden.)

If You want to validate the JSON use this online tool:

http://jsonlint.com/

Don't modify or delete the already created acme.js and amazon-formats.js;
simply duplicate, rename them with the .json extension, and then make them valid.

**Comment by gabrieledarrigo** [comment]
Another point:

can You please remove the repeated '20010 Canegrate MI' string from every address property?
We actually need only the street;
If We'd like to have a more complete data structure, especially for future edition of ACME I propose to use this:

```js
{
	"checked": false,
	"coords": [45.5738525, 8.9204629],
	"address": "Via Donato Bramante",
	"zip": "20010",
	"city": "Canegrate MI",
	"podcast": {
		"id": null
	}
}
```

Let me know.

G.

**Comment by gabrieledarrigo** [comment]
Good job dude,
going to merge!

**Pull request merged**
